// Runtime loader for the Tier-1 bundled official knowledge layer
// (knowledge/*.md + knowledge/index.json, generated by scripts/build-knowledge.mjs).
//
// License attribution (CC-BY-4.0, required to be reproduced):
// OpenHarmony documentation (openharmony/docs, © OpenHarmony Project Contributors), CC-BY-4.0 — https://creativecommons.org/licenses/by/4.0/
// The bundled files are unmodified excerpts (some trimmed to selected sections, each carrying an in-file excerpt note); per-file
// provenance (source commit, sha256, source URL) lives in knowledge/index.json.
import { readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

export const KNOWLEDGE_ATTRIBUTION = 'OpenHarmony documentation (openharmony/docs, © OpenHarmony Project Contributors), CC-BY-4.0 — https://creativecommons.org/licenses/by/4.0/'
export const KNOWLEDGE_LICENSE_URL = 'https://creativecommons.org/licenses/by/4.0/'

const BASE = join(dirname(fileURLToPath(import.meta.url)), '..', 'knowledge')
const INDEX_PATH = join(BASE, 'index.json')
const INTRO_CAP = 4000
const SECTION_CAP = 24000
const TOC_CAP = 150

// Line splitting without backslash escapes: CR?+LF (Windows/Unix line endings).
const NEWLINE_RE = new RegExp(String.fromCharCode(13) + '?' + String.fromCharCode(10))
const NEWLINE = String.fromCharCode(10)

let cache = null

export function available() { return existsSync(INDEX_PATH) }

export function loadIndex() {
  if (!cache) cache = JSON.parse(readFileSync(INDEX_PATH, 'utf8'))
  return cache
}

function meta() {
  const idx = loadIndex()
  return {
    source: idx.source,
    branch: idx.branch,
    sourceSha: idx.sourceSha,
    language: idx.language,
    license: idx.license,
    licenseUrl: idx.licenseUrl,
    attribution: idx.attribution,
    generatedAt: idx.generatedAt,
    totalBytes: idx.totalBytes,
  }
}

function entrySummary(e) {
  return {
    id: e.id,
    title: e.title,
    kind: e.kind,
    module: e.module,
    since: e.since,
    bytes: e.bytes,
    tags: e.tags,
    sourceUrl: e.sourceUrl,
    excerpted: e.excerpted === true,
    keptSections: Array.isArray(e.keptSections) ? e.keptSections.length : 0,
  }
}

// Parse '##'/'###' headings with 1-based line numbers.
const HEADING_RE = /^(#{2,3})[ ]+(.*)$/
export function headingsOf(text) {
  const out = []
  const lines = text.split(NEWLINE_RE)
  for (let i = 0; i < lines.length; i++) {
    const m = HEADING_RE.exec(lines[i])
    if (m) out.push({ level: m[1].length, text: m[2].trim(), line: i + 1 })
  }
  return out
}

function loadEntry(e) {
  const text = readFileSync(join(BASE, e.file), 'utf8')
  return { text, headings: headingsOf(text) }
}

function cut(text, cap) {
  if (text.length <= cap) return { text, truncated: false }
  return { text: text.slice(0, cap) + NEWLINE + '…[truncated ' + (text.length - cap) + ' chars]', truncated: true }
}

export function catalog(filter = '', kind = '') {
  const idx = loadIndex()
  const f = String(filter || '').toLowerCase()
  const k = String(kind || '')
  let entries = idx.entries
  if (k) entries = entries.filter((e) => e.kind === k)
  if (f) entries = entries.filter((e) => (e.id + ' ' + e.title + ' ' + e.module + ' ' + e.tags.join(' ')).toLowerCase().includes(f))
  return {
    ok: true,
    total: entries.length,
    ...meta(),
    entries: entries.map(entrySummary),
    note: 'Offline verbatim official docs (zh-CN). Version tags appear in the text as 起始版本/API version. For precise per-API classification use hms_api; for the full doc set use hms_docs.',
  }
}

export function search(keywords, limit = 6) {
  const idx = loadIndex()
  const kws = keywords.map((s) => s.toLowerCase())
  const scored = []
  for (const e of idx.entries) {
    const hay = (e.id + ' ' + e.title + ' ' + e.module + ' ' + e.tags.join(' ')).toLowerCase()
    let score = 0
    for (const kw of kws) if (hay.includes(kw)) score += 3
    let headingHits = []
    if (score < kws.length * 3) {
      // Fall through to headings when the topic itself did not fully match.
      const { headings } = loadEntry(e)
      for (const kw of kws) {
        const hits = headings.filter((h) => h.text.toLowerCase().includes(kw)).map((h) => h.text)
        for (const h of hits.slice(0, 2)) { headingHits.push(h); score += 1 }
      }
      headingHits = [...new Set(headingHits)]
    }
    if (score > 0) scored.push({ score, entry: e, headingHits: headingHits.slice(0, 6) })
  }
  scored.sort((a, b) => b.score - a.score)
  const results = scored.slice(0, limit).map((s) => ({ ...entrySummary(s.entry), score: s.score, matchedHeadings: s.headingHits }))
  return {
    ok: true,
    keywords,
    total: scored.length,
    ...meta(),
    results,
    note: results.length ? 'Use hms_knowledge action=read with an id to read the topic (TOC first, then a section by name).' : 'No matches. Try hms_api (SDK .d.ts) or hms_docs (devecocli docs search).',
  }
}

export function read(id, section = '') {
  const idx = loadIndex()
  const e = idx.entries.find((x) => x.id === id)
  if (!e) return { ok: false, error: 'unknown topic id: ' + id, knownIds: idx.entries.map((x) => x.id) }
  const { text, headings } = loadEntry(e)
  const toc = headings.slice(0, TOC_CAP).map((h, i) => ({ n: i + 1, level: h.level, text: h.text }))
  const base = {
    ok: true,
    id: e.id,
    title: e.title,
    kind: e.kind,
    module: e.module,
    since: e.since,
    file: e.file,
    bytes: e.bytes,
    headingTotal: headings.length,
    sourceUrl: e.sourceUrl,
    attribution: KNOWLEDGE_ATTRIBUTION,
  }
  if (section === '' || section == null) {
    const lines = text.split(NEWLINE_RE)
    const firstHeading = headings.length ? headings[0].line - 1 : lines.length
    const intro = cut(lines.slice(0, firstHeading).join(NEWLINE), INTRO_CAP)
    return {
      ...base,
      toc,
      tocTruncated: headings.length > TOC_CAP,
      intro: intro.text,
      introTruncated: intro.truncated,
      note: 'Pass section=<heading name or TOC n> to read one section (each section is capped at ' + SECTION_CAP + ' chars).',
    }
  }
  let idxSel = -1
  const n = Number(section)
  if (Number.isInteger(n) && n >= 1 && n <= headings.length) idxSel = n - 1
  else {
    const s = String(section).toLowerCase()
    const hit = headings.findIndex((h) => h.text.toLowerCase().includes(s))
    if (hit >= 0) idxSel = hit
  }
  if (idxSel < 0) return { ok: false, error: 'section not found: ' + section, hint: 'Read the TOC first (omit section) and pick a heading name or its n.', toc: toc.slice(0, 40) }
  const lines = text.split(NEWLINE_RE)
  const start = headings[idxSel].line - 1
  const end = idxSel + 1 < headings.length ? headings[idxSel + 1].line - 1 : lines.length
  const content = cut(lines.slice(start, end).join(NEWLINE), SECTION_CAP)
  return { ...base, section: headings[idxSel].text, sectionN: idxSel + 1, content: content.text, truncated: content.truncated, note: content.truncated ? 'Section truncated; ask for the next section by its TOC number.' : '' }
}
